services:
  - type: web
    name: book-recommendation-web
    env: python
    buildCommand: chmod +x deploy.sh && ./deploy.sh
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
